name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Upload Artifact
      run: dotnet nuget push "AuthenticatorServices/bin/Release/Insight.AuthenticatorServices.1.0.0.nupkg" --api-key fcaefde70895e47a208e033e434f3d708a9acfc5 --source "https://nuget.pkg.github.com/Insight-Services-APAC/index.json"
      

